### ISSUE TITLE
db ressource leak

### ISSUE THREAD

**Issue by mbogner** [mbogner/pg4wp2#3]
there seems to be a ressource leak with wordpress 4.1 and this code. at the moment i switched to mysql because i don't have the time to look into it and i think there is little interest in this topic anyway.

**Comment by hdijkema** [comment]
Hmm. I'm using it.

Hans Dijkema
Weerdslag 64
7206BT Zutphen

telefoon: 06 4639 0827
email: hans@dykema.nl mailto:hans@dykema.nl
Zakelijk: hans.dijkema@covalent.nl mailto:hans.dijkema@covalent.nl

Manuel schreef op 17-3-2015 om 21:03:

**Comment by mbogner** [comment]
If your apache isn't behaving like crazy (like mine) there shouldn't be a porblem. I've been using mysql since my last comment.
